function [Matrix_Pm_vv,Matrix_Pm_vs,Matrix_Pm_ss,...
         Matrix_Projm,Matrix_Nme] = fun_compute_matrices(N,Matrix_P0_m,...
                                                        Matrix_P0_e,...
                                                        G1_m,F1_m,F1_e,C1_m,...
                                                        Fac_Ed_loc_m,Aed_m,Led_m,...
                                                        Area_e,Area_m,Area_vol_m,...
                                                        ind_edge_free_mag,...
                                                        NGAUSS,nThread)
%%
mu_0=4*pi*1e-7;
%%
N_GAUSS1=NGAUSS;
N_GAUSS2=NGAUSS+1;
%%
N.node_con=0;
N.face_con=0;
F1_c=zeros(4,0);
Matrix_P0_c=zeros(0,3);
Area_c=zeros(0,1);
%%
[Matrix_Pm_vv] =    funPphiphi3_vv_for(N.node_mag,...
                                    N.face_mag,...
                                    Area_m.',...
                                    N_GAUSS1,...
                                    N_GAUSS2,...
                                    Matrix_P0_m,...
                                    F1_m,...                                           
                                    nThread,...
                                    Area_vol_m.');
Matrix_Pm_vv=(1/(mu_0))*Matrix_Pm_vv;
%%
[Matrix_Pm_vs] =   funPphiphi3_vs_for(N.node_mag,...
                                      N.edge_free_mag,...
                                      N_GAUSS1,...
                                      N_GAUSS2,...
                                      nThread,...
                                      N.face_mag,...                                      
                                      Matrix_P0_m,...
                                      G1_m(:,ind_edge_free_mag),...
                                      F1_m,...
                                      Area_m.',...
                                      Area_vol_m.');
Matrix_Pm_vs=(1/(mu_0))*Matrix_Pm_vs;                                                                      
%%
[Matrix_Pm_ss] = funPphiphi3_ss_for(N.node_mag,...
                                    N.edge_free_mag,...
                                    N_GAUSS1,...
                                    N_GAUSS2,...
                                    nThread,...
                                    Matrix_P0_m,...
                                    G1_m(:,ind_edge_free_mag),...
                                    Aed_m(ind_edge_free_mag).');
Matrix_Pm_ss=(1/(mu_0))*Matrix_Pm_ss;
%%
[Matrix_Projm] = funRrz_face2(N.face_mag,...
                                ones(N.face_mag,1),...
                                NGAUSS,...
                                Matrix_P0_m,...
                                F1_m,...
                                N.edge_mag,...
                                C1_m,...
                                Fac_Ed_loc_m,...
                                Aed_m,...
                                Led_m);
Matrix_Projm=sparse(Matrix_Projm);
[Matrix_Nme_ce] = funNme_for(N.node_con+N.node_ext,... 
                                N.face_con+N.face_ext,...
                                [Area_c;Area_e].',...
                                NGAUSS,...
                                N.node_mag,...
                                [Matrix_P0_c;Matrix_P0_e],...
                                [F1_c,N.node_con+F1_e],...
                                nThread,...
                                Matrix_P0_m);                         
inde=N.face_con+1:N.face_con+N.face_ext;                  
Matrix_Nme=Matrix_Nme_ce(:,inde);
end