function [lamDF_Ru] = fun_vec_lamDRu(param,lambda,u,...
                                        N,Matrix_P0_m,F1_m,...
                                        C1_m,Fac_Ed_loc_m,...
                                        Aed_m,Led_m,...
                                        nThread,...
                                        NGAUSS)
try
    lamDF_Ru=fun_compute_lamdRu_for(N.node_mag,N.face_mag,param',...
                                NGAUSS,Matrix_P0_m,F1_m,...
                                N.edge_mag,C1_m,Fac_Ed_loc_m,Aed_m.',Led_m.',...
                                nThread,lambda',u');  
catch ME
    warning(' FORTAN MEX-FILE is not supported, try to re-mex it in fortran/make_dRzr')
    warning([' MESSAGE ERROR:' ME.message]);
    return
end
end